### ISSUE TITLE
Could you please update cf-profile.pl to work with cf-agent 3.7.1?

### ISSUE THREAD

**Issue by atsaloli** [cfengineers-net/cf-profile#1]
# cf-agent -v --legacy-output -K  |  ./cf-profile.pl -a | tee /tmp/cf-profile.txt

cf-agent: unrecognized option '--legacy-output'
This program is currently working with legacy output of cfengine < 3.5.0. If you are on
cfengine >= 3.5.0, try using the -l or --legacy-output switches for cf-agent. at ./cf-profile.pl line 71, <STDIN> line 1.
# cf-agent -V

CFEngine Core 3.7.1
CFEngine Enterprise 3.7.1
[root@di-tlsmsdc01 ~]

**Comment by jonhenrik13** [comment]
Sorry for the late processing of this issue. I have been quite busy the past couple of months.  cf-profile is now 3.7-compatible in release 0.1.0. Please let me know of other issues you might come across.
